# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 95995c172ef348fa6d9e114f09ef70fe3bd6fc0d924fedff997639689c226c4c41c96b4b46a1d537d0bd045e9ded1340fe3fcd228c57fc5e4c4417cb1611861d

test:
  secret_key_base: 46e2565509ceb4eab6b846e7b2172de7f49976f8338805d553680a1942212c4c33de878370e96161bc2826583165c3283c0ce3680cc5ac399b261be37e1030dc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
